parcours_s3 = {
    "MU4IN250": "ANDROIDE",
    "MU4IN254": "ANDROIDE",
    "MU4IN258": "ANDROIDE",
    "MU4IN256": "ANDROIDE",
    "MU4IN257": "ANDROIDE",
    "MU4IN251": "ANDROIDE",
    "MU4IN252": "ANDROIDE",
    "MU4IN259": "ANDROIDE",
    "MU4IN852": "DAC",
    "MU4IN860": "DAC",
    "MU4IN861": "DAC",
    "MU4IN862": "DAC",
    "MU4IN863": "DAC",
    "MU4IN864": "DAC",
    "MU4IN868": "DAC",
}


parcours_s2 = {
    "DJ": "AND",
    "FoSyMa": "AND",
    "MU4IN202": "AND",
    "IHM": "AND",
    "RP": "AND",
    "RA": "AND",
    "RITAL": "DAC",
    "ML": "DAC",
    "MU4IN812": "DAC",
    "MU4IN811": "DAC",
    "IAMSI": "DAC",
    "SAM": "DAC",
    "IG3D": "IMA",
    "MU4IN910": "SFPN",
}
parcours_s1 = {
    "MOGPL": "AND",
    "IL": "STL",
    "LRC": "DAC",
    "MLBDA": "DAC",
    "MAPSI": "IMA",
    "AAGB": "BIM",
    "Maths": "BIM",
    "BIMA": "IMA",
    "PSCR": "SAR",
    "NOYAU": "SAR",
    "MOBJ": "SESI",
    "ESA": "SESI",
    "ARCHI": "SESI",
    "SIGNAL": "SESI",
    "VLSI": "SESI",
    "SC": "SFPN",
    "PPAR": "SFPN",
    "COMPLEX": "SFPN",
    "MODEL": "SFPN",
    "ALGAV": "STL",
    "DLP": "STL",
    "OUV": "STL",
}
