name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  js:
    name: JS Lint + Typecheck (Bun)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Lint (biome)
        run: bun run lint
      - name: Typecheck (tsc)
        run: bunx -y tsc --noEmit

  rust:
    name: Rust Fmt + Clippy + Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Build
        run: cargo build --workspace --all-targets
