name: Data Refresh

on:
  schedule:
    - cron: "30 06 * * 1,2,3,4,5"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: data-refresh-${{ github.ref }}
  cancel-in-progress: true

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Fetch ICS
        env:
          CAL_USERNAME: ${{ secrets.CAL_USERNAME }}
          CAL_PASSWORD: ${{ secrets.CAL_PASSWORD }}
        run: |
          npm run fetch

      - name: Preprocess JSON
        run: npm run preprocess

      - name: Squash and publish data commit
        run: |
          chmod +x scripts/publish-data.sh
          ./scripts/publish-data.sh
